# Generated by Django 4.1.3 on 2022-12-19 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0002_alter_bicycle_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicycle',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='bicyclestation',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Station name'),
        ),
        migrations.CreateModel(
            name='Trolley',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(verbose_name='User id')),
                ('usageTime', models.PositiveIntegerField(verbose_name='Rental time')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.bicycle', verbose_name='Bike')),
            ],
        ),
    ]
