# Generated by Django 4.1.3 on 2022-12-19 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_bicycle_user_alter_bicyclestation_name_trolley'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trolley',
            new_name='Order',
        ),
    ]
