# Generated by Django 4.1.3 on 2022-12-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicycle',
            name='user',
            field=models.PositiveIntegerField(default=0, verbose_name='Sharing user'),
        ),
    ]
