# Generated by Django 4.1.3 on 2022-12-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_alter_bicycle_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicycle',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/media/bicycles/', verbose_name='Bicycle photo'),
        ),
    ]
