# Generated by Django 4.1.3 on 2022-12-23 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_alter_bicycle_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='returnTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 12, 25, 47, 460558), verbose_name='Return time'),
        ),
    ]
