# Generated by Django 4.1.3 on 2022-12-23 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_order_returntime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='returnTime',
            field=models.DateTimeField(default=datetime.datetime(2001, 1, 1, 0, 0), verbose_name='Return time'),
        ),
    ]
