# Generated by Django 4.1.3 on 2022-12-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_alter_order_returntime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicycle',
            name='status',
            field=models.CharField(default='free', max_length=50, verbose_name='Status'),
        ),
    ]
